<?php

namespace TC\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function myFindAll()
	{
		$queryBuilder = $this
			->createQueryBuilder('u')
			->leftJoin('u.groups', 'g')
			->addSelect('g')
		;

		return $queryBuilder
			->getQuery()
			->getResult()
		;
	}

	public function research($value)
	{
		$queryBuilder = $this
		->createQueryBuilder('u')
		->leftJoin('u.groups', 'g')
			->addSelect('g')
		->where('u.username = :title')
		->orwhere('u.email = :title')
		->orwhere('u.id = :title')
		->orwhere('u.steam_id = :title')
				->setParameter('title', $value)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}
}
