<?php

namespace TC\WriterBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindAllArticles($page, $nbPerPage)
	{

		$query = $this
			->createQueryBuilder('a')
			->orderBy('a.date', 'DESC')
			->leftJoin('a.game', 'g')
			->addSelect('g')
			->where('a.published = :published')
			    ->setParameter('published', true)
		;

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function FindThisArticle($jeux, $id)
	{
		$queryBuilder = $this
			->createQueryBuilder('a')
			->leftJoin('a.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)
			->andWhere('a.id = :id')
				->setParameter('id', $id)
			->andWhere('a.published = :published')
			    ->setParameter('published', true)

		;

		return $queryBuilder
			->getQuery()
			->getResult()
		;
	}

	public function FindThisArticleAdmin($jeux, $id)
	{
		$queryBuilder = $this
			->createQueryBuilder('a')
			->leftJoin('a.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)
			->andWhere('a.id = :id')
				->setParameter('id', $id)

		;

		return $queryBuilder
			->getQuery()
			->getResult()
		;
	}

	public function FindArticles($maxresults)
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.date', 'DESC')
		->leftJoin('a.game', 'g')
		->addSelect('g')
		->where('a.published = :published')
			->setParameter('published', true)
		;

		$query
		->setMaxResults($maxresults)
		;
		return $query
			->getQuery()
			->getResult()
			;
	}

	public function FindGameArticles($jeux)
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.date', 'DESC')
		->leftJoin('a.game', 'g')
		->addSelect('g')
		->where('g.title = :title')
			->setParameter('title', $jeux)
		->andWhere('a.published = :published')
			    ->setParameter('published', true)
		;
		return $query
			->getQuery()
			->setMaxResults(4)
			->getResult()
			;
	}

		public function FindOtherArticles($jeux, $id)
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.date', 'DESC')
		->leftJoin('a.game', 'g')
		->addSelect('g')
		->where('a.id NOT LIKE :id')
		 ->setParameter('id', $id)
		->andWhere('g.title = :title')
		 ->setParameter('title', $jeux)
		->andWhere('a.published = :published')
			    ->setParameter('published', true)
		 ;

		 return $query
			->getQuery()
			->setMaxResults(4)
			->getResult()
			;
	}

	public function FindTagArticles($tag)
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.date', 'DESC')
		->leftJoin('a.tag', 't')
		->addSelect('t')
		->where('t.title = :title')
		 ->setParameter('title' , $tag)
		->andWhere('a.published = :published')
			    ->setParameter('published', true)
		 ;

		return $query
			->getQuery()
			->setMaxResults(4)
			->getResult()

		 ;
	}

		public function FindFiltredArticles($tag, $page, $nbPerPage)
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.date', 'DESC')
		->leftJoin('a.tag', 't')
		->addSelect('t')
		->where('t.title = :title')
		    ->setParameter('title' , $tag)
		->andWhere('a.published = :published')
			->setParameter('published', true)
		 ;

		 $query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function FindFiltredArticlesByGame($jeux, $page, $nbPerPage)
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.date', 'DESC')
		->leftJoin('a.game', 'g')
		->addSelect('g')
		->where('g.title = :title')
		    ->setParameter('title' , $jeux)
		->andWhere('a.published = :published')
			->setParameter('published', true)
		 ;

		 $query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function research($value)
	{
		$queryBuilder = $this
		->createQueryBuilder('a')
		->leftJoin('a.game', 'g')
			->addSelect('g')
		->where('a.title = :title')
		->orwhere('g.title = :title')
		->orwhere('a.id = :title')
		->orwhere('a.author = :title')
				->setParameter('title', $value)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}

		public function CountArticles()
	{
		$qb = $this
		->createQueryBuilder('a')
		->where('a.published = :published')
			    ->setParameter('published', true);

		$qb ->select($qb->expr()->count('a'))
		;

		return (int) $qb->getQuery()->getSingleScalarResult();
		 

	}

	public function FindArticlesUnpublished()
	{
		$queryBuilder = $this
		->createQueryBuilder('a')
		->where('a.published = :published')
			    ->setParameter('published', false);
		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}

	public function CountArticlesLastMonth()
	{
		$qb = $this
		->createQueryBuilder('a')
		->where('a.published = :published')
			    ->setParameter('published', true)
		->andWhere('a.date BETWEEN :start AND :end')
			->setParameter('end', new \DateTime('now'))
			->setParameter('start', new \DateTime('-30days'));

		$qb ->select($qb->expr()->count('a'))
		;

		return (int) $qb->getQuery()->getSingleScalarResult();
		 

	}

	public function CountArticlesByGame($jeux)
	{
		$qb = $this
		->createQueryBuilder('a')
		->leftJoin('a.game', 'g')
		    ->addSelect('g');
		$qb ->select($qb->expr()->count('a'))
		->where('g.title = :title')
				->setParameter('title', $jeux)
		;

		return (int) $qb->getQuery()->getSingleScalarResult();
		 

	}

	public function FindArticlesByAdminGame($jeux)
	{
		$queryBuilder = $this
		->createQueryBuilder('a')
		->leftJoin('a.game', 'g')
		    ->addSelect('g')
		->where('g.title = :title')
				->setParameter('title', $jeux)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;

	}

	public function researchFiltred($jeux, $value)
	{
		$queryBuilder = $this
		->createQueryBuilder('a')
		->leftJoin('a.game', 'g')
			->addSelect('g')
		->where('a.title = :value AND g.title LIKE :title')
		->orwhere('a.id = :value AND g.title LIKE :title')
		->orwhere('a.author = :value AND g.title LIKE :title')
				->setParameter('value', $value)
				->setParameter('title', $jeux)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}

	public function FindBestArticles()
	{
		$query = $this
		->createQueryBuilder('a')
		->orderBy('a.singularViewCount', 'DESC')
		->where('a.published = :published')
			    ->setParameter('published', true)
		->andWhere('a.singularViewCount NOT LIKE :countzero')
				->setParameter('countzero', 0)

		 ;

		 return $query
			->getQuery()
			->setMaxResults(5)
			->getResult()
			;
	}
}
