<?php

namespace TC\WriterBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindCategoryForThisGame($jeux)
	{
		$queryBuilder = $this
			->createQueryBuilder('c')
			->leftJoin('c.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)

		;
		return $queryBuilder
		->getQuery()
		->getResult()
		;

	}

	public function FindThisCategoryForThisGameForm($jeux, $category)
	{
		$queryBuilder = $this
			->createQueryBuilder('c')
			->Join('c.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)
			->andwhere('c.title = :titlecategory')
				->setParameter('titlecategory', $category)

		;

		return $queryBuilder
		;
	}

	public function FindThisCategoryForThisGame($jeux, $category)
	{
		$queryBuilder = $this
			->createQueryBuilder('c')
			->Join('c.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)
			->andwhere('c.title = :titlecategory')
				->setParameter('titlecategory', $category)

		;

		return $queryBuilder
		->getQuery()
		->getOneOrNullResult()
		;
	}

	public function FindCategoryForThisGameForm($jeux)
	{
		$queryBuilder = $this
			->createQueryBuilder('c')
			->leftJoin('c.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)

		;
		return $queryBuilder
		;

	}
}
