<?php

namespace TC\WriterBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * GamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindBestGames()
	{
		$query = $this
		->createQueryBuilder('g')
		->where('g.best = :best')
			->setParameter('best', TRUE)
		;

		return $query
			->getQuery()
			->getResult()
		;
	}

	public function FindThisGames($jeux)
	{
		$query = $this
		->createQueryBuilder('g')
		->where('g.title = :title')
			->setParameter('title', $jeux)
		;
		return $query
		->getQuery()
		->getResult()
		;
	}

	public function FindThisGamese($jeux)
	{
		$query = $this
		->createQueryBuilder('g')
		->where('g.title = :title')
			->setParameter('title', $jeux)
		;
		return $query
		;
	}

	public function research($value)
	{
		$queryBuilder = $this
		->createQueryBuilder('g')
		->where('g.title = :title')
		->orwhere('g.id = :title')
		->orwhere('g.editor = :title')
				->setParameter('title', $value)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}
}
