<?php

namespace TC\WriterBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindAllNews($page, $nbPerPage)
	{

		$query = $this
			->createQueryBuilder('n')
			->orderBy('n.date', 'DESC')
			->leftJoin('n.game', 'g')
			->addSelect('g')
			->where('n.published = :published')
			    ->setParameter('published', true)
		;

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function FindThisNews($jeux, $id)
	{
		$queryBuilder = $this
			->createQueryBuilder('n')
			->leftJoin('n.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)
			->andWhere('n.id = :id')
				->setParameter('id', $id)
			->andWhere('n.published = :published')
			    ->setParameter('published', true)
		;

		return $queryBuilder
			->getQuery()
			->getResult()
		;
	}

	public function FindThisNewsAdmin($jeux, $id)
	{
		$queryBuilder = $this
			->createQueryBuilder('n')
			->leftJoin('n.game', 'g')
			->addSelect('g')
			->where('g.title = :title')
				->setParameter('title', $jeux)
			->andWhere('n.id = :id')
				->setParameter('id', $id)
		;

		return $queryBuilder
			->getQuery()
			->getResult()
		;
	}

	public function FindNews($maxresults)
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.date', 'DESC')
		->leftJoin('n.game', 'g')
		->addSelect('g')
		->where('n.published = :published')
			->setParameter('published', true)
		;

		$query
		->setMaxResults($maxresults)
		;
		return $query
			->getQuery()
			->getResult()
			;
	}

	public function FindGameNews($jeux)
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.date', 'DESC')
		->leftJoin('n.game', 'g')
		->addSelect('g')
		->where('g.title = :title')
			->setParameter('title', $jeux)
		->andWhere('n.published = :published')
			->setParameter('published', true)
		;

		return $query
			->getQuery()
			->setMaxResults(6)
			->getResult()
			;
	}
	public function FindOtherNews($jeux, $id)
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.date', 'DESC')
		->leftJoin('n.game', 'g')
		->addSelect('g')
		->where('n.id NOT LIKE :id')
		    ->setParameter('id', $id)
		->andWhere('g.title = :title')
		    ->setParameter('title', $jeux)
		->andWhere('n.published = :published')
			->setParameter('published', true)
		 ;

		 return $query
			->getQuery()
			->setMaxResults(3)
			->getResult()
			;
	}

	public function FindTagNews($tag)
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.date', 'DESC')
		->leftJoin('n.tag', 't')
		->addSelect('t')
		->where('t.title = :title')
		 ->setParameter('title' , $tag)
		->andWhere('n.published = :published')
			->setParameter('published', true)
		 ;

		return $query
			->getQuery()
			->setMaxResults(6)
			->getResult()

		 ;
	}

	public function FindFiltredNews($tag, $page, $nbPerPage)
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.date', 'DESC')
		->leftJoin('n.tag', 't')
		->addSelect('t')
		->where('t.title = :title')
		    ->setParameter('title' , $tag)
		->andWhere('n.published = :published')
			->setParameter('published', true)
		 ;

		 $query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function FindFiltredNewsByGame($jeux, $page, $nbPerPage)
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.date', 'DESC')
		->leftJoin('n.game', 'g')
		->addSelect('g')
		->where('g.title = :title')
		    ->setParameter('title' , $jeux)
		->andWhere('n.published = :published')
			->setParameter('published', true)
		 ;

		 $query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}

	public function research($value)
	{
		$queryBuilder = $this
		->createQueryBuilder('n')
		->leftJoin('n.game', 'g')
			->addSelect('g')
		->where('n.title = :title')
		->orwhere('g.title = :title')
		->orwhere('n.id = :title')
		->orwhere('n.author = :title')
				->setParameter('title', $value)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}

	public function CountNews()
	{
		$qb = $this
		->createQueryBuilder('n')
		->where('n.published = :published')
			    ->setParameter('published', true);

		$qb ->select($qb->expr()->count('n'))
		;

		return (int) $qb->getQuery()->getSingleScalarResult();
		 

	}

	public function FindNewsUnpublished()
	{
		$queryBuilder = $this
		->createQueryBuilder('n')
		->where('n.published = :published')
			    ->setParameter('published', false);
		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}

	public function CountNewsLastMonth()
	{
		$qb = $this
		->createQueryBuilder('n')
		->where('n.published = :published')
			    ->setParameter('published', true)
		->andWhere('n.date BETWEEN :start AND :end')
			->setParameter('end', new \DateTime('now'))
			->setParameter('start', new \DateTime('-30days'));

		$qb ->select($qb->expr()->count('n'))
		;

		return (int) $qb->getQuery()->getSingleScalarResult();
		 

	}
	public function CountNewsByGame($jeux)
	{
		$qb = $this
		->createQueryBuilder('n')
		->leftJoin('n.game', 'g')
		    ->addSelect('g');
		$qb ->select($qb->expr()->count('n'))
		->where('g.title = :title')
				->setParameter('title', $jeux)
		;

		return (int) $qb->getQuery()->getSingleScalarResult();
		 

	}

	public function FindNewsByAdminGame($jeux)
	{
		$queryBuilder = $this
		->createQueryBuilder('n')
		->leftJoin('n.game', 'g')
		    ->addSelect('g')
		->where('g.title = :title')
				->setParameter('title', $jeux)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;

	}

	public function researchFiltred($jeux, $value)
	{
		$queryBuilder = $this
		->createQueryBuilder('n')
		->leftJoin('n.game', 'g')
			->addSelect('g')
		->where('n.title = :value AND g.title LIKE :title')
		->orwhere('n.id = :value AND g.title LIKE :title')
		->orwhere('n.author = :value AND g.title LIKE :title')
				->setParameter('value', $value)
				->setParameter('title', $jeux)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}

	public function FindBestNews()
	{
		$query = $this
		->createQueryBuilder('n')
		->orderBy('n.singularViewCount', 'DESC')
		->where('n.published = :published')
			    ->setParameter('published', true)
		->andWhere('n.singularViewCount NOT LIKE :countzero')
				->setParameter('countzero', 0)

		 ;

		 return $query
			->getQuery()
			->setMaxResults(5)
			->getResult()
			;
	}

}
