<?php

namespace TC\WriterBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function research($value)
	{
		$queryBuilder = $this
		->createQueryBuilder('t')
		->where('t.title = :title')
		->orwhere('t.id = :title')
				->setParameter('title', $value)
		;

		return $queryBuilder
		    ->getQuery()
		    ->getResult()
		  ;
	}
}
